### ISSUE TITLE
Kotlin Modding tutorial

### ISSUE THREAD

**Issue by Immortalin** [Emberwalker/GenericEngineering#1]
Hi, can you create a tutorial on Minecraft modding with kotlin and a comparison with using java?

**Comment by Wyldern** [comment]
I really should make a blog actually. Yeah, I probably should. I also need to update the Pulsar documentation. I'll make a note to do so, thanks!

**Comment by Wyldern** [comment]
Done! http://drakon.io/#!/post/2015/10/01/kotlin-and-you/
